### ISSUE TITLE
problema na execução do django

### ISSUE THREAD

**Issue by renatogcruz** [renatoprovi/Test-Driven-Development-with-Python#1]
Há um erro ao executar o comando `python manage.py runserver`. 

O erro indica um problema de sintaxe em um arquivo chamado `widgets.py` na linha 151. O erro específico é "`Generator expression must be parenthesized`".

Isso sugere que há um problema com uma expressão geradora (generator expression) que não está devidamente parêntesada. As expressões geradoras devem ser parêntesadas quando usadas em contextos específicos.

Como o Django 1.11.3 não é mais suportado e pode conter vulnerabilidades de segurança, seria recomendável atualizar para uma versão mais recente do Django. Mas, como o projeto segue os passos de um livro, isso poderia causar problemas de compatibilidades futuras.

Então, se você precisar manter essa versão específica, uma solução seria modificar o arquivo `widgets.py` para corrigir o problema.

No código, o trecho de código que está causando o problema está em `widgets.py`, na linha 151:

```python
related_url += '?' + '&amp;'.join(
    '%s=%s' % (k, v) for k, v in params.items(),
)
```

Pode ser corrigido isso envolvendo a expressão geradora entre parênteses:

```python
related_url += '?' + '&amp;'.join(
    ('%s=%s' % (k, v)) for k, v in params.items()
)
```

Essa alteração adiciona parênteses em torno da expressão `%s=%s' % (k, v)`, eliminando assim o erro relacionado à necessidade de parênteses na expressão geradora.

Após essa alteração, o trecho de código corrigido deve ser:

```python
related_url += '?' + '&amp;'.join(
    ('%s=%s' % (k, v)) for k, v in params.items()
)
```

Isso deve resolver o problema!

**Comment by renatoprovi** [comment]
Issue #1 FECHADA.

Problema solucionado utilizando a parte do código sugerida:

```
related_url += '?' + '&amp;'.join(
    ('%s=%s' % (k, v)) for k, v in params.items()
)
```

**Comment by renatoprovi** [comment]
Issue https://github.com/renatoprovi/Test-Driven-Development-with-Python/issues/1 FECHADA.
